# SPDX-License-Identifier: MIT

[package]
name = "vscode-workspace-gen"
version = "0.1.0"
edition = "2021"
exclude = [
    ".github/*",
    "vscode*"
]

[dependencies]
clap = { version = "4.5.0", features = ["derive"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.115", features = ["preserve_order", "indexmap"] }
