# SPDX-License-Identifier: MIT

name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          cargo test

      - name: Run tests (Qt)
        run: |
          cargo test --features qt
