# SPDX-License-Identifier: MIT

name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build Release
        run: |
          cargo build --release

      - name: Build Debug
        run: |
          cargo build

      - name: Run tests
        run: |
          cargo test
