# SPDX-License-Identifier: MIT

name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          cargo test --no-default-features

      - name: Run tests (Qt)
        run: |
          cargo test --no-default-features --features qt
